export const FETCH_ROOM_LIST = "FETCH_ROOM_LIST";
export const FETCH_ROOM_LIST_SUCCESS = "FETCH_ROOM_LIST_SUCCESS";
export const FETCH_ROOM_LIST_FAILURE = "FETCH_ROOM_LIST_FAILURE";
export const SHOW_BOOKING_FORM = "SHOW_BOOKING_FORM";
