export const FETCH_ROOM_LIST = 'FETCH_ROOM_LIST';
export const FETCH_ROOM_LIST_SUCCESS = 'FETCH_ROOM_LIST_SUCCESS';
export const FETCH_ROOM_LIST_FAILURE = 'FETCH_ROOM_LIST_FAILURE';
export const SHOW_BOOKING_FORM = 'SHOW_BOOKING_FORM';
export const BOOK_ROOM = 'BOOK_ROOM';
export const BOOK_ROOM_SUCCESS = 'BOOK_ROOM_SUCCESS';
export const BOOK_ROOM_FAILURE = 'BOOK_ROOM_FAILURE';
